[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
DISABLE_LOGGING = "false" 
DISABLE_RATE_LIMIT = "true"
DEFAULT_LOCALE = "en"
FILE_FIELD_ADAPTER = "local"
DISABLE_CAPTCHA = "true"
USE_LOCAL_FEATURE_FLAGS = "true"
NOTIFICATION__SEND_ALL_MESSAGES_TO_CONSOLE = "true"
WORKER_CONCURRENCY = "10"